// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl0e9ZTrzFK8PeQR8hNAR4dpgI4yWD164',
    appId: '1:520224849696:web:53dfa9a1079c9c86e2e145',
    messagingSenderId: '520224849696',
    projectId: 'grocery-app-1ed1e',
    authDomain: 'grocery-app-1ed1e.firebaseapp.com',
    storageBucket: 'grocery-app-1ed1e.firebasestorage.app',
    measurementId: 'G-0HKYYZ827V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_4h-bt6zadkws95-W_PhizQA5GHX-6dM',
    appId: '1:520224849696:android:0970e6e16300c672e2e145',
    messagingSenderId: '520224849696',
    projectId: 'grocery-app-1ed1e',
    storageBucket: 'grocery-app-1ed1e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO0L3e9c-BidPVikLE1MTV9yY8l-FsTXs',
    appId: '1:520224849696:ios:81b997e15e828f23e2e145',
    messagingSenderId: '520224849696',
    projectId: 'grocery-app-1ed1e',
    storageBucket: 'grocery-app-1ed1e.firebasestorage.app',
    iosBundleId: 'com.example.groceryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBO0L3e9c-BidPVikLE1MTV9yY8l-FsTXs',
    appId: '1:520224849696:ios:81b997e15e828f23e2e145',
    messagingSenderId: '520224849696',
    projectId: 'grocery-app-1ed1e',
    storageBucket: 'grocery-app-1ed1e.firebasestorage.app',
    iosBundleId: 'com.example.groceryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCl0e9ZTrzFK8PeQR8hNAR4dpgI4yWD164',
    appId: '1:520224849696:web:b51415ee661b24e4e2e145',
    messagingSenderId: '520224849696',
    projectId: 'grocery-app-1ed1e',
    authDomain: 'grocery-app-1ed1e.firebaseapp.com',
    storageBucket: 'grocery-app-1ed1e.firebasestorage.app',
    measurementId: 'G-NLFP52SZND',
  );
}
